version: '3.9'

services:
  node-container:
    container_name: node-scraper
    image: node:16-buster
    user: 'node:node'
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    working_dir: '/app'
    command: ["/bin/bash"]

      
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      #- LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}   only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"